### ISSUE TITLE
[FEATURE] <description>

### ISSUE THREAD

**Issue by payallenka** [IceCreamMC/IceCream#10]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I can write the docker file for this repository, with default data useful for later puposes.

### Proposed Solution

create a docker file and specify the configurations and port numbers.

### Do you want to work on this issue?

Yes

**Comment by Pan-cakse** [comment]
Sorry for the late response but sure you can make it!

**Comment by payallenka** [comment]
Hi,
Unfortunately there is a slight issue as I won't be able to complete this
task due to some academic work from the college and personal reasons.
Please close the issue to re-assign to someone deserving .

I deeply apologise for the inconvenience caused.

Regards
Payal Lenka

**Comment by Pan-cakse** [comment]
Alr fine with me
