### ISSUE TITLE
Add Issue Template and PR Template 

### ISSUE THREAD

**Issue by Devanshukoli** [IceCreamMC/IceCream#3]
Hey! Just checked out the project. And It's really cool. Would Love to work on it and contribute as well
Just noticed that the project is missing **Issue Template** and **PR Templates**. and I would like to add them into the project. Such that New folx can easily create *Issues* and *PR's* as well, without much of head banging...

**Comment by Pan-cakse** [comment]
Hmm never made them before but I can try to make them

**Comment by Devanshukoli** [comment]
Well, I was wondering If I can work on it.

**Comment by Pan-cakse** [comment]
> Well, I was wondering If I can work on it.

Hmmmmm, sure I can let you do it!

**Comment by Pan-cakse** [comment]
Completed will be closed
