### ISSUE TITLE
Code of CONDUCT file is missing 

### ISSUE THREAD

**Issue by anshgautam-github** [IceCreamMC/IceCream#6]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Yes,

### Proposed Solution

i can make a code of conduct file, as a Code of Conduct file in a project outlines the expectations for behavior within the community, promoting a respectful, inclusive, and collaborative environment. It helps set clear boundaries and guidelines on how members should interact, ensuring a positive experience for everyone involved.

### Do you want to work on this issue?

Yes

**Comment by Pan-cakse** [comment]
Alr sure you can make it!
