### ISSUE TITLE
[BUG] Enhancement of NavBar

### ISSUE THREAD

**Issue by payallenka** [IceCreamMC/IceCream#9]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

In the deployed site.

### Version of website/mobile (for example "v1.2.3")

latest deployed version

### Description

![image](https://github.com/user-attachments/assets/c124abf3-683d-413e-86cd-3992fa636256)
When I saw the website I realized congested navbar. The spacing and margins set aren't right. Kindly assign me this issue under Hacktoberfest to set right spacing, margin (in general alignment) of the site under hacktoberfest tag. 

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. Go to <replace your> page.
1. On top right side, close to the <Account> menu
1. Some menu are not working properly.
1. Continue...

If you don't know exact steps, include any relevant details like:

- What page you were on...
- What you were trying to do...
- What went wrong...

### Do you want to work on this issue?

Yes

**Comment by Pan-cakse** [comment]
Sorry for the late response but sure you can do it make sure to the Website repo!

**Comment by payallenka** [comment]
Hi,
Unfortunately there is a slight issue as I won't be able to complete this
task due to some academic work from the college and personal reasons.
Please close the issue to re-assign to someone deserving .

I deeply apologise for the inconvenience caused.

Regards
Payal Lenka

**Comment by Pan-cakse** [comment]
Alr thats fine with me
